# Generated by Django 3.2.8 on 2021-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211028_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
    ]
